FROM python:3.11-slim

WORKDIR /app

RUN pip install fastapi uvicorn redis aio-pika httpx

COPY gateway/gateway_main.py /app/main.py

EXPOSE 8002

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]